<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260308171232 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ad_amenity (ad_id INT NOT NULL, amenity_id INT NOT NULL, PRIMARY KEY (ad_id, amenity_id))');
        $this->addSql('CREATE INDEX IDX_662A90E74F34D596 ON ad_amenity (ad_id)');
        $this->addSql('CREATE INDEX IDX_662A90E79F9F1305 ON ad_amenity (amenity_id)');
        $this->addSql('CREATE TABLE amenity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, icon VARCHAR(100) DEFAULT NULL, group_name VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AB607963989D9B62 ON amenity (slug)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)');
        $this->addSql('CREATE TABLE favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, ad_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68C58ED9A76ED395 ON favorite (user_id)');
        $this->addSql('CREATE INDEX IDX_68C58ED94F34D596 ON favorite (ad_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_favorite_user_ad ON favorite (user_id, ad_id)');
        $this->addSql('ALTER TABLE ad_amenity ADD CONSTRAINT FK_662A90E74F34D596 FOREIGN KEY (ad_id) REFERENCES ad (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ad_amenity ADD CONSTRAINT FK_662A90E79F9F1305 FOREIGN KEY (amenity_id) REFERENCES amenity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED94F34D596 FOREIGN KEY (ad_id) REFERENCES ad (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ad ADD max_guests INT NOT NULL');
        $this->addSql('ALTER TABLE ad ADD address VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE ad ADD city VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE ad ADD country VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE ad ADD latitude DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE ad ADD longitude DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE ad ADD is_published BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE ad ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE ad ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE ad ADD category_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ad ALTER price TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE ad ADD CONSTRAINT FK_77E0ED5812469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_77E0ED58989D9B62 ON ad (slug)');
        $this->addSql('CREATE INDEX IDX_77E0ED5812469DE2 ON ad (category_id)');
        $this->addSql('ALTER TABLE booking ADD status VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE booking ADD guests_count INT NOT NULL');
        $this->addSql('ALTER TABLE booking ADD cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE booking ADD cancellation_reason TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE booking ALTER start_date TYPE DATE');
        $this->addSql('ALTER TABLE booking ALTER end_date TYPE DATE');
        $this->addSql('ALTER TABLE booking ALTER amount TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT fk_9474526c4f34d596');
        $this->addSql('ALTER TABLE comment ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE comment ADD booking_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C4F34D596 FOREIGN KEY (ad_id) REFERENCES ad (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C3301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9474526C3301C60 ON comment (booking_id)');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT fk_c53d045f4f34d596');
        $this->addSql('ALTER TABLE image ADD position SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE image ADD is_primary BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE image ALTER caption DROP NOT NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F4F34D596 FOREIGN KEY (ad_id) REFERENCES ad (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD phone VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD is_host BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE users ADD is_verified BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE users ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE users ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE users ALTER introduction DROP NOT NULL');
        $this->addSql('ALTER TABLE users ALTER description DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9989D9B62 ON users (slug)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ad_amenity DROP CONSTRAINT FK_662A90E74F34D596');
        $this->addSql('ALTER TABLE ad_amenity DROP CONSTRAINT FK_662A90E79F9F1305');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED9A76ED395');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED94F34D596');
        $this->addSql('DROP TABLE ad_amenity');
        $this->addSql('DROP TABLE amenity');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE favorite');
        $this->addSql('ALTER TABLE ad DROP CONSTRAINT FK_77E0ED5812469DE2');
        $this->addSql('DROP INDEX UNIQ_77E0ED58989D9B62');
        $this->addSql('DROP INDEX IDX_77E0ED5812469DE2');
        $this->addSql('ALTER TABLE ad DROP max_guests');
        $this->addSql('ALTER TABLE ad DROP address');
        $this->addSql('ALTER TABLE ad DROP city');
        $this->addSql('ALTER TABLE ad DROP country');
        $this->addSql('ALTER TABLE ad DROP latitude');
        $this->addSql('ALTER TABLE ad DROP longitude');
        $this->addSql('ALTER TABLE ad DROP is_published');
        $this->addSql('ALTER TABLE ad DROP created_at');
        $this->addSql('ALTER TABLE ad DROP updated_at');
        $this->addSql('ALTER TABLE ad DROP category_id');
        $this->addSql('ALTER TABLE ad ALTER price TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE booking DROP status');
        $this->addSql('ALTER TABLE booking DROP guests_count');
        $this->addSql('ALTER TABLE booking DROP cancelled_at');
        $this->addSql('ALTER TABLE booking DROP cancellation_reason');
        $this->addSql('ALTER TABLE booking ALTER start_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE booking ALTER end_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE booking ALTER amount TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C4F34D596');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C3301C60');
        $this->addSql('DROP INDEX UNIQ_9474526C3301C60');
        $this->addSql('ALTER TABLE comment DROP updated_at');
        $this->addSql('ALTER TABLE comment DROP booking_id');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT fk_9474526c4f34d596 FOREIGN KEY (ad_id) REFERENCES ad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F4F34D596');
        $this->addSql('ALTER TABLE image DROP position');
        $this->addSql('ALTER TABLE image DROP is_primary');
        $this->addSql('ALTER TABLE image ALTER caption SET NOT NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT fk_c53d045f4f34d596 FOREIGN KEY (ad_id) REFERENCES ad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP INDEX UNIQ_1483A5E9E7927C74');
        $this->addSql('DROP INDEX UNIQ_1483A5E9989D9B62');
        $this->addSql('ALTER TABLE users DROP phone');
        $this->addSql('ALTER TABLE users DROP is_host');
        $this->addSql('ALTER TABLE users DROP is_verified');
        $this->addSql('ALTER TABLE users DROP created_at');
        $this->addSql('ALTER TABLE users DROP updated_at');
        $this->addSql('ALTER TABLE users ALTER introduction SET NOT NULL');
        $this->addSql('ALTER TABLE users ALTER description SET NOT NULL');
    }
}
